#debug : true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
   # driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false
    username: shou66
    password: shou66
  redis:
    host: 127.0.0.1 
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
   # lettuce:
     # shutdown-timeout: 0
    

    
mapper:
  mappers:
  #  - tk.mybatis.mapper.common.Mapper
  #not-empty: false
  #identity: MYSQL
  
#公共配置与profiles选择无关
mybatis:
  #typeAliasesPackage: springboot.hello.entity
  mapperLocations: classpath:springboot/hello/mapper/**/*.xml

# 打印sql
logging:
  path: d:\logs
  level:
    root: info  #低于info级别的就不显示  TRACE < DEBUG < INFO < WARN < ERROR
    springboot.hello : debug
    
    
  
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

pros:
  pakage : springboot.hello.query